controller_list:
  - name: fake_cr5_gripper_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses.
  - group: cr5_gripper_robot
    pose: home
  - group: gripper
    pose: close