# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: cr5_gripper_robot
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: cr5_gripper_robot
    action_ns: joint_controller/follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - finger_joint

arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - finger_joint
  gains:
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
# hand_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - left_inner_finger_joint
#     - left_inner_knuckle_joint
#     - right_inner_finger_joint
#     - right_inner_knuckle_joint
#     - right_outer_knuckle_joint
    #- left_outer_finger_joint
